### ISSUE TITLE
Compiler Error regarding flircamera.cpp

### ISSUE THREAD

**Issue by SpindleMS** [syntalos/syntalos#9]
Hi again,

Thank you for getting back to me regarding the the previous issue, I'm now running into a compiler error regarding flircamera.cpp and meson-generated_moc_flircamsettingsdialog.cpp.  I'll attach the compiler output as a txt file to keep the comment thread clean.

--Mike
[camera-flir_compiler_error.txt](https://github.com/user-attachments/files/16431578/camera-flir_compiler_error.txt)

**Comment by ximion** [comment]
Addressed via https://github.com/syntalos/syntalos/discussions/11#discussioncomment-10214883 :-)
